#!/usr/bin/env python3
"""Measure excess high-frequency residual on known controlled textures.

Projects the known clean texture out of each decoded grain-on frame. The
remaining residual includes quantization error: it is neither a pure grain
measurement nor an HDR perceptual score. The mask is specific to the named
768x432 fixtures generated by fidelity_compare.py.
"""
import argparse
import json
from pathlib import Path
import statistics

import numpy as np

from production_compare import sha
from quality_metrics import LumaReader, highpass


CASES = {'detail_fine', 'detail_coarse', 'detail_weak', 'woven_detail',
         'woven_motion', 'woven_coarse', 'pq_detail', 'pq_woven'}


def checked_reader(path, info, digest):
    if sha(path) != digest:
        raise RuntimeError('Changed raw artifact: ' + str(path))
    reader = LumaReader(path, info['width'], info['height'], info['bits'])
    if reader.frames != info['frames']:
        raise RuntimeError('Incorrect raw frame count: ' + str(path))
    return reader


def measure(report, root, reference):
    if not report.get('complete'):
        raise ValueError('Controlled comparison is incomplete')
    rows = []
    for case in report['cases']:
        if case['name'] not in CASES:
            continue
        name, info = case['name'], case['source']
        width, height = info['width'], info['height']
        if (width, height) != (768, 432) or info['frames'] <= 8:
            raise ValueError('Unexpected controlled texture geometry')
        source = checked_reader(reference / name / 'source.yuv', info,
                                info['hashes']['source.yuv'])
        ideal = checked_reader(reference / name / 'ideal.yuv', info,
                               info['hashes']['ideal.yuv'])
        mask = np.zeros((height, width), dtype=bool)
        for band in range(1, 11):
            mask[24:height // 2 - 24, band * 64 + 16:(band + 1) * 64 - 16] = True
        clean = [highpass(ideal.luma(frame))[mask] for frame in range(8, info['frames'])]
        sigmas = [float((highpass(source.luma(frame))[mask] - texture).std())
                  for frame, texture in zip(range(8, info['frames']), clean)]
        baseline = case['baseline']
        encoded = Path(baseline['command'][baseline['command'].index('-o') + 1])
        entries = [('production', encoded.parent, baseline)]
        entries += [(key, root / name / key, case['arms'][key])
                    for key in ['max-0.5-qp20', 'max-0.1-qp20', 'max-0-qp20']
                    if key in case['arms']]
        matched = case.get('within_production_size')
        if matched and matched not in {entry[0] for entry in entries}:
            entries.append((matched, root / name / matched, case['arms'][matched]))
        row = dict(name=name, arms={})
        for arm, directory, evidence in entries:
            off, on = [checked_reader(directory / f'grain-{grain}.yuv', info,
                                      evidence['decoded_hashes'][f'grain-{grain}.yuv'])
                       for grain in [0, 1]]
            ratios, gains = [], []
            for frame, texture, sigma in zip(range(8, info['frames']), clean, sigmas):
                denominator = float(np.sum(texture * texture))
                if not denominator > 0 or not sigma > 0:
                    raise ValueError('Texture projection has no signal')
                base = highpass(off.luma(frame))[mask]
                rendered = highpass(on.luma(frame))[mask]
                gains.append(float(np.sum(base * texture)) / denominator)
                rendered_gain = float(np.sum(rendered * texture)) / denominator
                ratios.append(float((rendered - rendered_gain * texture).std()) / sigma)
            row['arms'][arm] = dict(median_base_detail_gain=statistics.median(gains),
                median_hf_residual_ratio=statistics.median(ratios),
                min_hf_residual_ratio=min(ratios), max_hf_residual_ratio=max(ratios))
        rows.append(row)
        print(name, {key: round(value['median_hf_residual_ratio'], 3)
                     for key, value in row['arms'].items()}, flush=True)
    if len(rows) != len(CASES) or {row['name'] for row in rows} != CASES:
        raise ValueError('Requires all eight unique texture cases')
    return rows


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--report', type=Path, required=True)
    parser.add_argument('--reference', type=Path, required=True)
    parser.add_argument('--output', type=Path, required=True)
    args = parser.parse_args()
    if args.output.exists():
        parser.error('Output already exists')
    report = json.loads(args.report.read_text())
    result = dict(complete=False, scope=__doc__, report_sha256=sha(args.report),
                  harness_sha256=sha(__file__), cases=[])
    try:
        result['cases'] = measure(report, args.report.parent, args.reference)
        result['complete'] = True
    except Exception as error:
        result['error'] = str(error)
        raise
    finally:
        args.output.write_text(json.dumps(result, indent=2) + '\n')


if __name__ == '__main__':
    main()
